### PR TITLE
Update vi-VN.json

### PR DESCRIPTION
**Pull request by ngocanhtve**
Full translation.

### CODE REVIEW

**Comment by mateusz-bak** [comment]
Hi @ngocanhtve thank you for your great work! Although can you update the translations through [Weblate](https://hosted.weblate.org/projects/openreads/app-strings/vi/)? It will be much easier for people to review the translations.

**Comment by ngocanhtve** [comment]
Sorry, I don't have time to deal with weblate.

**Comment by mateusz-bak** [comment]
No worries, maybe someone else can find this useful. Thanks anyway

**Comment by ngocanhtve** [comment]
Don't worry, I don't see anything useful. You only accept suggestions on Weblate - I've suggested quite a few string - although it feels quite sick, not accepting Github pull requests. Using open source software is to avoid dictators, but what is happening makes you no different from dictator.

**Comment by ngocanhtve** [comment]
Have you noticed anything yet? No one pays attention to the Vietnamese translation on the weblate. While I'm here, I have fully translated it and make a pr, you did not accept it for the reason that other people can't vote for it. But obviously if there are changes from the source it will still be updated to the weblate and everyone else can see and vote.

Why does it have to be a weblate, when there is a full translation here?

**Pull request closed without merging**
