### PR TITLE
323 bug the number of editions displayed when choosing a book is wrong

### PR DESCRIPTION
**Pull request by apobrt**
Previously, it showed a wrong number of editions for every result. This PR fix this

### CODE REVIEW

**Comment by apobrt** [comment]
Closes also #180

**Comment by mateusz-bak** [comment]
Hmm I checked and it still displays wrong editions count.

For example try to search "mythos stephen fry" and check editions for the blue book.

**Comment by apobrt** [comment]
I found the reason of the mismatch: I show all editions returned by Open Library, but when they are displayed , they are filtered out if they don't have a cover image. 

So, for example, "mythos stephen fry", in the fifth result, show correctly 10 results, but only 6 have the cover (see: https://openlibrary.org/books/OL28643252M/Mythos).

So now my doubt is: what we want to show? Only the ones with the covers? Or all of them?
Maybe all, but sorting first the ones with the cover.

A book without a cover is ugly, but it could be useful to avoid to manually insert all the info (maybe it lacks only the cover)..

**Comment by mateusz-bak** [comment]
Good finds, I think that showing all of the editions, even without covers makes most sense (I see majority voted the same in the Matrix channel). 

On the ones with missing covers - I would go with displaying them as they actually are - so without the covers. And to differentiate we could do title, author and release of the specific edition (as you suggested before). 

In the future we need to come up with a system to add covers to books without them.

**Review by mateusz-bak — APPROVED** [review]

**Pull request merged**
