### PR TITLE
Add a dropdown to select from existing tags

### PR DESCRIPTION
**Pull request by vbh**
This PR add an autocomplete text view to TagField which allows user to select a tag from existing tags while editing/adding a book

### CODE REVIEW

**Comment by mateusz-bak** [comment]
Hi, great work, thank you!

I'm checking it right now and I have some points:
- I  cannot scroll the extended list of tags,
- the dropdown seems to be non resizable - (when there's only 1 match it takes same amount of screen as with 5 matches),

Optionally would be awesome if the view could scroll a little to the top so the user sees the dropdown when it is behind the keyboard.

Maybe you want to experiment with this package? https://pub.dev/packages/flutter_typeahead

**Comment by mateusz-bak** [comment]
Hi @vbh  please rebase your branch as it does not work on Flutter 3.10.5 after I updated master. If that's a problem let me know and I will try to just take the changes you made there.

**Comment by mateusz-bak** [comment]
Just tested, works great! I really like that it shows all available tags at the beginning.

One thing though. Do you think it would be possible to hide the dropdown when no matching tags found instead of showing "No Items Found!"?

**Comment by mateusz-bak** [comment]
Unfortunately I have two issues

1. When the list of tags is empty the drop down is shown for a couple of milliseconds. I suppose this is nothing really serious as user will see the flicker only when adding first book with a tag.
https://github.com/mateusz-bak/openreads-android/assets/32651935/0b903566-81ed-471e-ab46-701db90d3a6b

2. I cannot select any tags from the dropdown on my OnePlus 8T. It works on the emulator, I'll debug this more to check what's causing this. Did you test it on a physical device?
https://github.com/mateusz-bak/openreads-android/assets/32651935/840bf312-408a-42b2-91e2-ad409aa73058

**Comment by vbh** [comment]
> When the list of tags is empty the drop down is shown for a couple of milliseconds

drop down is shown on loading as well, have disabled that. This should be fixed now.

> I cannot select any tags from the dropdown on my OnePlus 8T.

Can you check if accessibility is turned **on** on your device? It is working as expected on my device only when accessibility is **off**. There is an similar issue reported in flutter_typeahead [#463](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463).

I've tried out [this](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463#issuecomment-1460966010l) workaround suggested in the same issue. This is working, but this will have an effect on accessibility service.

**Comment by mateusz-bak** [comment]
Yeah it's the accessibility for password manager. Works good with the workaround. We need to keep an eye if the issue in flutter_typeahead is resolved. Merging now, thanks! :rocket:

**Pull request merged**
